// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-saved-view/internal/sdk/models/shared"
	"net/http"
)

type GetSavedViewRequest struct {
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSavedViewRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetSavedViewResponseBody - A generic error returned by the API
type GetSavedViewResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *GetSavedViewResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetSavedViewResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetSavedViewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	SavedViewItem *shared.SavedViewItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *GetSavedViewResponseBody
}

func (o *GetSavedViewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSavedViewResponse) GetSavedViewItem() *shared.SavedViewItem {
	if o == nil {
		return nil
	}
	return o.SavedViewItem
}

func (o *GetSavedViewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSavedViewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSavedViewResponse) GetObject() *GetSavedViewResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
