// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-saved-view/internal/sdk/models/shared"
	"net/http"
)

type PatchSavedViewRequest struct {
	SavedViewPartial *shared.SavedViewPartial `request:"mediaType=application/json"`
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PatchSavedViewRequest) GetSavedViewPartial() *shared.SavedViewPartial {
	if o == nil {
		return nil
	}
	return o.SavedViewPartial
}

func (o *PatchSavedViewRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type PatchSavedViewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	SavedViewItem *shared.SavedViewItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchSavedViewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchSavedViewResponse) GetSavedViewItem() *shared.SavedViewItem {
	if o == nil {
		return nil
	}
	return o.SavedViewItem
}

func (o *PatchSavedViewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchSavedViewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
