// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SavedViewItem - A saved entity view
type SavedViewItem struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// Generated uuid for a saved view
	ID *string `json:"id,omitempty"`
	// User-friendly identifier for the saved view
	Name string `json:"name"`
	// boolean property for if a view is shared with organisation
	Shared *bool `json:"shared,omitempty"`
	// list of schemas a view can belong to
	Slug      []string `json:"slug"`
	UIConfig  any      `json:"ui_config"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

func (o *SavedViewItem) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *SavedViewItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SavedViewItem) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SavedViewItem) GetShared() *bool {
	if o == nil {
		return nil
	}
	return o.Shared
}

func (o *SavedViewItem) GetSlug() []string {
	if o == nil {
		return []string{}
	}
	return o.Slug
}

func (o *SavedViewItem) GetUIConfig() any {
	if o == nil {
		return nil
	}
	return o.UIConfig
}

func (o *SavedViewItem) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
