// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SavedView - A saved entity view
type SavedView struct {
	// User-friendly identifier for the saved view
	Name string `json:"name"`
	// boolean property for if a view is shared with organisation
	Shared *bool `json:"shared,omitempty"`
	// list of schemas a view can belong to
	Slug     []string `json:"slug"`
	UIConfig any      `json:"ui_config"`
}

func (o *SavedView) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SavedView) GetShared() *bool {
	if o == nil {
		return nil
	}
	return o.Shared
}

func (o *SavedView) GetSlug() []string {
	if o == nil {
		return []string{}
	}
	return o.Slug
}

func (o *SavedView) GetUIConfig() any {
	if o == nil {
		return nil
	}
	return o.UIConfig
}
