// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-saved-view/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SavedViewDataSourceModel) RefreshFromSharedSavedViewItem(resp *shared.SavedViewItem) {
	if resp != nil {
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.ID = types.StringPointerValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.Shared = types.BoolPointerValue(resp.Shared)
		r.Slug = []types.String{}
		for _, v := range resp.Slug {
			r.Slug = append(r.Slug, types.StringValue(v))
		}
		uiConfigResult, _ := json.Marshal(resp.UIConfig)
		r.UIConfig = types.StringValue(string(uiConfigResult))
		r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
	}
}
