// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-saved-view/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-saved-view/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &SavedViewDataSource{}
var _ datasource.DataSourceWithConfigure = &SavedViewDataSource{}

func NewSavedViewDataSource() datasource.DataSource {
	return &SavedViewDataSource{}
}

// SavedViewDataSource is the data source implementation.
type SavedViewDataSource struct {
	client *sdk.SDK
}

// SavedViewDataSourceModel describes the data model.
type SavedViewDataSourceModel struct {
	CreatedAt types.String   `tfsdk:"created_at"`
	ID        types.String   `tfsdk:"id"`
	Name      types.String   `tfsdk:"name"`
	Shared    types.Bool     `tfsdk:"shared"`
	Slug      []types.String `tfsdk:"slug"`
	UIConfig  types.String   `tfsdk:"ui_config"`
	UpdatedAt types.String   `tfsdk:"updated_at"`
}

// Metadata returns the data source type name.
func (r *SavedViewDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_saved_view"
}

// Schema defines the schema for the data source.
func (r *SavedViewDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "SavedView DataSource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `View id`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `User-friendly identifier for the saved view`,
			},
			"shared": schema.BoolAttribute{
				Computed:    true,
				Description: `boolean property for if a view is shared with organisation`,
			},
			"slug": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `list of schemas a view can belong to`,
			},
			"ui_config": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *SavedViewDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *SavedViewDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *SavedViewDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var id string
	id = data.ID.ValueString()

	request := operations.GetSavedViewRequest{
		ID: id,
	}
	res, err := r.client.SavedViews.GetSavedView(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.SavedViewItem != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedSavedViewItem(res.SavedViewItem)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
